### ISSUE TITLE
Heavy images are slow but background-color may help legibility

### ISSUE THREAD

**Issue by Askoth** [gururs/gururs#20]
The image inside the <div /> with class "backstretch" is a heavy one. Thats not a problem but the problem is that the background stays white while the image is not loaded.

That may take some time (as it did to me) and I couldn't read the text because it was also white.

If a background-color is set with a dark color following the palette of the site the text will be legible even before the image shows.

**Comment by josemarluedke** [comment]
I totally agree with you. I'm working to solve this right now!
